language: python
install: skip

sudo: required

#branches:
#  only:
#    - master

services:
  - docker
env:
  global:
    - REGISTRY_USER=compss
    - secure: ""

before_script:
    - docker build --pull --cache-from bscwdc/dislib --tag bscwdc/dislib .
    - docker run $(bash <(curl -s https://codecov.io/env)) -d --name dislib bscwdc/dislib 
       
script: "docker exec dislib bash run_tests.sh"
script: "docker exec dislib bash run_coverage.sh"

after_success:
  - docker exec dislib codecov --token=629589cf-e257-4262-8ec0-314dfd98f003
after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push bscwdc/dislib
  on:
    branch: master


